name: NixOS Flake Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-flake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v16
      - run: nix flake check

  build-configs:
    needs: check-flake
    runs-on: ubuntu-latest
    strategy:
      matrix:
        host: [sam-main, framework13, AIServer]
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v16
      - name: Dry-run Build
        run: nix build .#nixosConfigurations.${{ matrix.host }}.config.system.build.toplevel --dry-run
